---
  deployment:
    tasks:
      - export DEPLOYPATH=/home/gorel/public_html/consultaqr.regionloreto.gob.pe/
      - /bin/rsync -av public/ $DEPLOYPATH
      - export DEPLOYPATH=/home/gorel/consultaqr/
      - /bin/rsync -av ./ $DEPLOYPATH
