---
  deployment:
    tasks:
      - export DEPLOYPATH=/home/gorel/public_html/consultapj.regionloreto.gob.pe/
      - /bin/rsync -av public/ $DEPLOYPATH
      - export DEPLOYPATH=/home/gorel/consultapj/
      - /bin/rsync -av ./ $DEPLOYPATH
